apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout')
]

apps/success/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index')
]

logReg/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace = 'user')),
    url(r'^success/', include('apps.success.urls', namespace = 'success')),   
]

apps/login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import re, bcrypt
from django.db import models
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your models here.
class UserManager(models.Manager):
    def add_user(self, data):
        errors = []
        if not data['first']:
            errors.append('First name is required!')
        if not data['first'].isalpha():
            errors.append('First name must have alpha characters only!')
        if len(data['first']) < 2:
            errors.append('First Name must be at least 2 characters long.')
        if not data['last']:
            errors.append('Last name is required!')
        if not data['last'].isalpha():
            errors.append('Last name must have alpha characters only!')
        if len(data['last']) < 2:
            errors.append('Last Name must be at least 2 characters long.')
        if not EMAIL_REGEX.match(data['email']):
            errors.append('A valid email is required.')
        if len(data['password']) < 8:
            errors.append('Password must be at least 8 characters long.')
        if data['password'] != data['confirm']:
            errors.append('Password did not match Confirm')
        if self.filter(email=data['email']):
            errors.append('Email already exists')

        response = {}

        if errors:
            response['status'] = False
            response['errors'] = errors
        else:
            response['status'] = True
            hashed_password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            user = self.create(first = data['first'], last = data['last'], email = data['email'], password = hashed_password)
            response['user'] = user
        return response
    def check_user(self, data):
        user = self.filter(email=data['email'])
        response = {}
        if user:
            if bcrypt.checkpw(data['password'].encode(), user[0].password.encode()):
                response['status'] = True
                response['user'] = user[0]
            else:
                response['status'] = False
                response['errors'] = 'Invalid email/password combination.'
        else:
            response['status'] = False
            response['errors'] = 'Email does not exist'
        return response
        
class User(models.Model):
    first = models.CharField(max_length=255)
    last = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/success/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from .models import User
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, 'login/index.html')

def register(request):
    if request.method == 'POST':
        newUser = User.objects.add_user(request.POST)
        if newUser['status']:
            request.session['first'] = newUser['user'].first
            request.session['word'] = "Registered"
            return redirect('success:index')

        else:
            for error in newUser['errors']:
                messages.error(request, error)
            return redirect('user:index')
    
    else:
        return redirect('user:index')

def login(request):
    if request.method == 'POST':
        user = User.objects.check_user(request.POST)
        if user['status']:
            request.session['first'] = user['user'].first
            request.session['word'] = "Logged In"
            return redirect('success:index')
        else:
            messages.error(request, user['errors'])
            return redirect('user:index')
    else:
        return redirect('user:index')


def logout(request):
    if request.method == 'POST':
        request.session.clear()
    return redirect('user:index')

apps/success/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect

# Create your views here.
def index(request):
    if 'first' not in request.session:
        return redirect('user:index')
    return render(request, 'success/index.html')

apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login &amp; Reg | Home</title>
</head>
<body>
    <fieldset class="forms registration">
        <legend>Registration</legend>
        <table>
            <form action="{% url 'user:register' %}" method="post">
                {% csrf_token %}
            <tr>
                <td><label for="">First Name:</label></td>
                <td><input type="text" name="first"></td>
            </tr>
            <tr>
                <td><label for="">Last Name:</label></td>
                <td><input type="text" name="last"></td>
            </tr>
            <tr>
                <td><label for="">Email:</label></td>
                <td><input type="text" name="email"></td>
            </tr>
            <tr>
                <td><label for="">Password:</label></td>
                <td><input type="password" name="password"></td>
            </tr>
            <tr>
                <td><label for="">Confirm:</label></td>
                <td><input type="password" name="confirm"></td>
            </tr>
            <tr>
                <td><input type="submit" name="action" value="Register"></td>
            </tr>
            </form>
        </table>
    </fieldset>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <fieldset class="forms login">
        <legend>Login</legend>
        <table>
            <form action="{% url 'user:login' %}" method="post">
                {% csrf_token %}
            <tr>
                <td><label for="">Email:</label></td>
                <td><input type="text" name="email"></td>
            </tr>
            <tr>
                <td><label for="">Password:</label></td>
                <td><input type="password" name="password"></td>
            </tr>
            <tr>
                <td><input type="submit" name="action" value="Login"></td>
            </tr>
            </form>
        </table>
    </fieldset>
</body>
</html>

apps/success/templates/success/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login &amp; Reg | Success</title>
</head>
<body>
    <h1>Success! Welcome {{ request.session.first }}</h1>
    <p><span style="color:green">You have successfully {{request.session.word}}</span></p>
    <form action="{% url 'user:logout' %}">
        {% csrf_token %}
        <input type="submit" value="Logout">
    </form>
</body>
</html>